monitor/main/routes.py
from flask import Blueprint

import os
from flask import render_template, request, flash, redirect, url_for, request
from monitor.monitoring import monitor_website, ping
from monitor.models import CheckedWebsite, updateDatabase
from sqlalchemy import desc

from monitor.main.utils import contact_mail

main = Blueprint('main', __name__, static_folder='static', static_url_path='/main/static') #static_folder='static', static_url_path='/main/static


@main.route("/", methods=['GET', 'POST'])
def index():
    return render_template('index.html', title="Website monitoring that saves your time!")


@main.route("/blog", methods=('GET', 'POST'))
def blog():
        return render_template('blog.html', title="Blog | ServerMonitor")


@main.route("/thankyou", methods=('GET', 'POST'))
def thankyou():
    return render_template('thankyou.html', title="Thank You! | ServerMonitor")

@main.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404




#=========================================
# Routes for PWA-Files
#=========================================

@main.route("/offline.html")
def offline():
    return main.send_static_file('offline.html')


@main.route("/service-worker.js")
def sw():
    return main.send_static_file('service-worker.js')


@main.route("/app.js")
def app():
    return main.send_static_file('app.js')


@main.route("/manifest.json")
def manifest():
    return main.send_static_file('manifest.json')

monitor/users/routes.py
from flask import Blueprint

import os
import secrets
from PIL import Image
from flask import render_template, request, flash, redirect, url_for, request, jsonify
from monitor import db, bcrypt, mail
from monitor.monitoring import check_latency
from monitor.models import User, ContiniousMonitoring
from monitor.users.forms import SignUpForm, SignInForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm, AddWebsiteForm, DeleteAccountForm
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail  import Message
from sqlalchemy import desc

import time
import json
from datetime import datetime

from monitor.users.utils import save_picture, send_reset_email, send_verification_email

users = Blueprint('users', __name__)


@users.route("/signup", methods=('GET', 'POST'))
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = SignUpForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your Account has been created! You are now able to login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('signup.html', title="Sign Up | ServerMonitor", form=form)


@users.route("/login", methods=('GET', 'POST'))
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = SignInForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            user.last_login = datetime.utcnow()
            user.login_count += 1
            user.last_ip = request.environ.get('HTTP_X_REAL_IP', request.remote_addr) #BUG: Doesnt work right now. Need config NGINX?
            #print(request.environ.get('HTTP_X_REAL_IP', request.remote_addr))
            db.session.commit()
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash(f'Login Unsuccessful! Please check email and password', 'danger')
    return render_template('login.html', title="Sign In | ServerMonitor", form=form)


@users.route("/logout", methods=['POST', 'GET'])
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/account", methods=('GET', 'POST'))
@login_required
def account():
    form = UpdateAccountForm()
    account_deletion_form = DeleteAccountForm()
    
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pictures/' + current_user.image_file)

    if account_deletion_form.validate_on_submit():
        if account_deletion_form.confirmation.data == current_user.email:
            user = User.query.filter_by(email=current_user.email).first()
            db.session.delete(user)
            logout_user()
            db.session.commit()
            flash('Your account has been successfully deleted. See you next time.', 'info')
        else:
            flash('Error', 'danger')
        return redirect(url_for('main.index'))

    return render_template('account.html', title="Your Account | ServerMonitor", image_file=image_file, form=form, deletion_form=account_deletion_form)


@users.route("/reset_password", methods=('GET', 'POST'))
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title="Reset Password | ServerMonitor", form=form)


@users.route("/reset_password/<token>", methods=('GET', 'POST'))
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        user.last_password_reset = datetime.utcnow()
        user.password_reset_count += 1
        db.session.commit()
        flash(f'Your password has been updated! You are now able to login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title="Reset Password | ServerMonitor", form=form)



@users.route("/websites", methods=('GET', 'POST'))
@login_required
def my_websites():
    form = AddWebsiteForm()
    if form.validate_on_submit():
        if form.name.data and form.website_url.data != '':
            website = ContiniousMonitoring(user_id=current_user.id, website_name=form.name.data, website_url=form.website_url.data, isRunning=form.monitoring_activated.data, response_time='0000', up_time='0000')
            db.session.add(website)
            db.session.commit()
            flash(f'Website Added', 'success')
        return redirect(url_for('users.my_websites'))
        #return render_template('my_websites.html', title="My Websites | ServerMonitor", form=form, website_query=website_query)
    
    website_query = ContiniousMonitoring.query.order_by(desc(ContiniousMonitoring.creation_date)).limit(10).all()
    return render_template('my_websites.html', title="My Websites | ServerMonitor", form=form, current_user_id=current_user.id, website_query=website_query)



#/monitoring only shows the graphs of the selected website
#TODO
@users.route("/monitoring/<string:website_url>", methods=('GET', 'POST'))
@login_required
def monitoring(website_url):
    return render_template('monitoring.html', title="Monitor your websites | ServerMonitor", website_url=website_url)#, website_url=mon.website_url, monitoring_name=mon.website_name, data_responsetime=list(v.values()))
    
    
    
    '''
    form = AddWebsiteForm()

    data_responsetime = {
        "0000": 0,
        "0100": 0,
        "0200": 0,
        "0300": 0,
        "0400": 0,
        "0500": 0,
        "0600": 0,
        "0700": 0,
        "0800": 0,
        "0900": 0,
        "1000": 0,
        "1100": 0,
        "1200": 0,
        "1300": 0,
        "1400": 0,
        "1500": 0,
        "1600": 0,
        "1700": 0,
        "1800": 0,
        "1900": 0,
        "2000": 0,
        "2100": 0,
        "2200": 0,
        "2300": 0,
        "2400": 0
    }
    data_uptime = {
        "0000": 0,
        "0100": 0,
        "0200": 0,
        "0300": 0,
        "0400": 0,
        "0500": 0,
        "0600": 0,
        "0700": 0,
        "0800": 0,
        "0900": 0,
        "1000": 0,
        "1100": 0,
        "1200": 0,
        "1300": 0,
        "1400": 0,
        "1500": 0,
        "1600": 0,
        "1700": 0,
        "1800": 0,
        "1900": 0,
        "2000": 0,
        "2100": 0,
        "2200": 0,
        "2300": 0,
        "2400": 0
    }

    if form.validate_on_submit():
        current_hour = datetime.utcnow().hour
        current_hour_mil = str(current_hour) + '00'
        data_responsetime[current_hour_mil] = check_latency(form.website_url.data)
        
        response_time_json = json.dumps(data_responsetime)
        response_time_dict = json.loads(response_time_json)
        #data_responsetime.append(json.dumps({'current time': (check_latency(form.website_url.data))}))
        #t = json.dumps({'current time': (check_latency(form.website_url.data))})
        monitoring = ContiniousMonitoring(user_id=current_user.id, website_name=form.name.data, website_url=form.website_url.data, isRunning=form.monitoring_activated.data, response_time=response_time_json, up_time='leer')
        db.session.add(monitoring)
        db.session.commit()
        flash(f'\"{form.name.data}\" has been created!', 'success')
        
        return render_template('monitoring.html', title="Monitor your websites | ServerMonitor", form=form, website_url=form.website_url.data, monitoring_name=form.name.data, data_responsetime=list(response_time_dict.values()), data_uptime=data_responsetime)

    
    #mon = ContiniousMonitoring.query.filter_by(id=1).first()
    
    #print(mon.response_time)

    #s = json.loads(mon.response_time)
    #s['2400'] = check_latency(mon.website_url)
    #mon.response_time = json.dumps(s)

    #db.session.commit()
    #print(s.values())

    #v = json.loads(mon.response_time)

    '''

    

monitor/templates/base.html
<!doctype html>
<html lang="en" style="width:100%; height:100%; margin:0;">
  <head>

    <!-- Manifest JSON-->
    <link rel="manifest" href="{{ url_for('main.static', filename='manifest.json') }}">
    <!-- End Manifest JSON -->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-113171051-2"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-113171051-2', { 'optimize_id': 'GTM-NP39F2Q'});
    </script>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="language" content="en">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#ed8936">

    <!-- Meta Desctiption for Search -->
    <meta name="description" content="► Offline for everyone or just for me? Easily check the status of websites with ServerMonitor! ✅">
    <meta name="title" content="Is the website online? - ServerMonitor"/>
    <meta property="og:description" content="► Offline for everyone or just for me? Easily check the status of websites with ServerMonitor! ✅"/>
    <meta property="og:title" content="Is the website online? - ServerMonitor"/>
    <meta name="twitter:description" content="► Offline for everyone or just for me? Easily check the status of websites with ServerMonitor! ✅">
    <meta name="twitter:title" content="Is the website online? - ServerMonitor"/>


    <link rel="shortcut icon" href="/static/img/favicon.ico">
    <link rel="stylesheet" href="/static/css/main.css">


    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">-->


    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">



    <title>{% block title %}{% endblock %}</title>
  </head>
  <body class="bg-white">
    <div id="container mx-auto">
        <nav class="flex items-center justify-between flex-wrap bg-white p-4 sticky top-0">
          <a href="{{url_for('main.index')}}">
            <div class="flex items-center flex-shrink-0 text-gray-900 mr-6">
                <img src="/static/img/icon.svg" width="30" height="30" class="fill-current h-8 w-8 mr-2" alt="">
              <span class="font-bold text-xl tracking-tight text-gray-700">ServerMonitor <span class="font-thin text-orange-700">BETA</span></span>
            </div>
          </a>
            <div class="block lg:hidden">
              <button class="flex items-center px-3 py-2 border rounded text-gray-900 border-gray-900 hover:text-gray hover:border-gray" onclick="toggle()">
                <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
              </button>
            </div>
            <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto hidden" id="menu">
              <div class="text-sm lg:flex-grow">
                <!--<a href="" class="font-medium block mt-4 lg:inline-block lg:mt-0 text-gray-800 hover:text-gray-600 mr-4">
                  Info
                </a>-->
                <a href="{{ url_for('main.blog') }}" class="font-medium block mt-4 lg:inline-block lg:mt-0 text-gray-800 hover:text-gray-600">
                  Blog
                </a>
              </div>
              <div>
                {% if current_user.is_authenticated %}
                <div class="relative sm:block">
                  <button onclick="openMenu()" class="block h-8 w-8 rounded-full overflow-hidden border-2 border-gray-300 focus:outline-none focus:border-orange-500">
                    <img class="h-full w-full object-cover" src="{{ url_for('static', filename='profile_pictures/' + current_user.image_file) }}" alt="Profile image">
                  </button>
                    <div id="menuDiv" style="display: none" class="absolute right-0 mt-2 w-48 bg-gray-200 text-gray-800 shadow-md rounded-lg py-2">
                      <a href="{{ url_for('users.account') }}" class="block px-4 py-1 hover:bg-orange-200">Account</a>
                      <a href="{{ url_for('users.my_websites') }}" class="block px-4 py-1 hover:bg-orange-200">Websites</a>
                      <a href="{{ url_for('users.logout') }}" class="block px-4 py-1 hover:bg-orange-200">Log Out</a>
                    </div>
                </div> 
                {% else %}
                <a class="inline-block text-sm px-4 py-2 leading-none border rounded text-gray-800 border-gray-800 hover:border-transparent hover:text-white hover:bg-gray-600 mt-4 lg:mt-0" href="{{ url_for('users.login') }}">Log In</a>
                <a class="inline-block text-sm px-4 py-2 leading-none border rounded text-white bg-orange-500 border-orange-500 hover:border-transparent hover:text-orange-500 hover:border-orange-500 hover:bg-white mt-4 lg:mt-0" href="{{ url_for('users.signup') }}">Sign Up</a>
                {% endif %}
              </div>
            </div>
          </nav>
          {% block content%}{% endblock %}
      <footer class="bg-gray-300 bottom-0">
        <div class="footer-copyright text-center py-10 text-gray-900 font-semibold">Made with ❤ in Germany
          <p>Powered by InspiredProgrammer</p>
          <a href="mailto:chris@inspiredprogrammer.com">chris@inspiredprogrammer.com</a>
          <p>© 2019</p>
        </div>
      </footer>
    </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


  <!-- Google Analytics -->
  <script async src="https://www.google-analytics.com/analytics.js"></script>

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  
  ga('create', 'UA-113171051-2', 'auto');
  ga('send', 'pageview');
  </script>
  <!-- End Google Analytics -->

  <script src="{{ url_for('main.static', filename='app.js') }}"></script>

  <script>
    const menu = document.getElementById('menu');
    const toggle = () => menu.classList.toggle("hidden");
  </script>

  <script>
    function openMenu(){
      var menu = document.getElementById("menuDiv");
      if (menu.style.display === "none"){
        menu.style.display = "block";
      } else {
        menu.style.display = "none";
      }
    }
  </script>

</body>
</html>

monitor/templates/index.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="md:flex content-start bg-white px-12 md:px-20 py-10">
  <div class="md:w-1/2 xl:py-40 lg:py-20 md:py-20 lg:pr-20">
    <!--<h1 class="text-3xl sm:text-3xl md:text-4xl lg:text-5xl xl:text-5xl font-bold text-gray-800 leading-tight">Website monitoring as simple as posting on Instagram!</h1>-->
    <h1 class="text-3xl sm:text-3xl md:text-4xl lg:text-5xl xl:text-5xl font-bold text-gray-800 leading-tight">Website monitoring that saves your time!</h1>
    <p class="py-4 md:py-8 font-light text-xl md:text-xl text-left text-gray-600 pr-16 md:pr-0">Getting real time data, insights and alerts about your website anywhere and anytime immediatly through SMS and E-Mail.</p>
    <div>
      <!-- Email Octopus -->
      <form method="post"
        action="https://emailoctopus.com/lists/21c15f58-e49e-11e9-be00-06b4694bee2a/members/embedded/1.3/add"
        class="email-octopus-form"
        data-sitekey="6LdYsmsUAAAAAPXVTt-ovRsPIJ_IVhvYBBhGvRV6">
      <div class="container">
          <div class="block lg:inline-block email-octopus-form-row">
              <input class="w-64 py-2 px-4 rounded border focus:outline-none focus:border-orange-500 text-orange-500" id="field_0" name="field_0" type="email" placeholder="Your Email">
          </div>
          <div class="block hidden email-octopus-form-row-hp" aria-hidden="true">
              <!-- Do not remove this field, otherwise you risk bot sign-ups -->
              <input type="text" name="hp21c15f58-e49e-11e9-be00-06b4694bee2a"
                 tabindex="-1"
                 autocomplete="nope">
          </div>
          <div class="block lg:inline-block email-octopus-form-row-subscribe">
              <input type="hidden"
                  name="successRedirectUrl"
                  value="{{ url_for('main.thankyou') }}">
              <button class="text-xl shadow-md font-medium bg-orange-500 hover:bg-orange-700 text-white sm:mt-2 md:mt-0 py-2 px-4 rounded">Tell me when it's available!</button>
          </div>
      </div>
      </form>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
      <script src="https://emailoctopus.com/bundles/emailoctopuslist/js/1.3/recaptcha.js"></script>
      <script src="https://emailoctopus.com/bundles/emailoctopuslist/js/1.3/formEmbed.js"></script>
      <!-- Email Octopus End -->
    </div>
  </div>
  <div class="w-1/3 mt-8 block justify-center items-center mx-auto flex md:visible lg:visible xl:visible">
    <img class="min-w-1/2 xl:max-w-3xl lg:max-w-lg md:max-w-sm md:pl-10 md:pr-20 lg:pr-0" src="/static/img/undraw_google.svg" alt="">
  </div>
</div>
<div class="bg-gray-200 p-10 text-gray-900">
  <div>
    <h2 class="pb-10 text-center text-gray-800 text-3xl font-bold">Monitor your website without a lot of work</h2>
    <div class="container justify-center items-center mx-auto flex pb-20">
      <div class="block md:inline-block bg-white rounded shadow p-4 m-2">
        <img class="object-fill" src="static/img/undraw_user_flow_vr6w.svg" alt="">
        <h4 class="font-bold text-center pt-20">Adding your website in a single and simple workflow</h4>
        <p class="pt-2 text-center text-gray-700 font-normal">Setup monitoring for your website in one simple workflow that takes no time.</p>
      </div>
      <div class="block md:inline-block bg-white rounded shadow p-4 m-2">
        <img src="static/img/undraw_preferences_uuo2.svg" alt="">
        <h4 class="font-bold text-center pt-20">Customize, how and when you want to be informed</h4>
        <p class="pt-2 text-center text-gray-700 font-normal">Get the necessary information about your website only when needed and how you want.</p>
      </div>
      <div class="block md:inline-block bg-white rounded shadow p-4 m-2">
        <img src="static/img/undraw_site_stats_l57q.svg" alt="">
        <h4 class="font-bold text-center pt-20">Inform your users trough status pages</h4>
        <p class="pt-2 text-center text-gray-700 font-normal">A status page informs your users at any time.</p>
      </div>
    </div>
  </div>
</div>

<!--- ### JavaScript ### -->
<script>
    document.getElementById('button-addon2').addEventListener('click', myFunction);

    function myFunction(){
      $("#loadingmask").fadeTo(2, 0.3);
    }
</script>

<script>
  function checkHost(){
    var h = document.getElementById('url').value.toLowerCase();
    h = h.startsWith("http://")? h.substring(7): h
    h = h.startsWith("https://") ? h.substring(8) : h
    h = h.indexOf("/") > 0 ? h.substring(0,h.indexOf("/")) : h
    var domain = '/' + h;
    console.log(domain)
    window.location = h;
    console.log(window.location)
    return false;
  };
</script>



{% endblock %}

monitor/templates/login.html
{% extends 'base.html' %}

{% block title %}Log In | ServerMonitor{% endblock %}

{% block content %}
<div class="flex bg-white shadow-2xl mx-64 my-20 rounded overflow-hidden">
    <div class="container w-1/2 bg-orange-200">
        <div class="relative">
            <img class="object-cover h-full w-full" src="/static/img/Flat-Mountains.svg" alt="">
            <div class="absolute top-0 pl-48 pt-40 text-white">
                    <h1 class="font-bold text-4xl">Hello!</h1>
                    <p class="font-medium">Log in to continue access</p>
                </div>
            
        </div>
    </div>
    <div class="inline w-1/2 p-4">
        <h1 class="pt-10 pl-10 text-3xl font-bold text-gray-800">Log In</h1>
        <form class="p-10" method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="">
                    <div class="flex items-center border-b border-b-2 border-orange-500 py-2">
    
                        {% if form.email.errors %}
                        {{ form.email(class="appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none bg-white", placeholder="Email") }}
                    {% endif %}     
    
                    </div>
                    <div class="flex items-center border-b border-b-2 border-orange-500 py-2">
    
                        {% if form.password.errors %}
                        {{ form.password(class="appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="appearance-none pt-4 bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none bg-white", placeholder="Password") }}
                    {% endif %}     
                    </div>
                    <div class="pt-4">
                        {{ form.remember(class="") }}
                        {{ form.remember.label(class="text-gray-800 font-medium") }}
                    </div>
                </fieldset>
                <div class="form-group pt-4">
                    {{ form.submit(class="bg-orange-500 hover:bg-orange-400 text-white font-bold py-2 px-4 rounded inline-flex items-center") }}
                    <small class="text-gray-600 hover:text-gray-800">
                        <a class="ml-2" href="{{url_for('users.reset_request')}}">Reset password</a>
                    </small>
                </div>
            </form>
    </div>
</div>

<!-- <div class="mx-auto container shadow-sm bg-white rounded">
    <div class="content-section card-body">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log in to your Account</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                    {{ form.email(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control") }}
                {% endif %}     

                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                    {{ form.password(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control") }}
                {% endif %}     
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted">
                    <a class="ml-2" href="{{url_for('users.reset_request')}}">Reset password</a>
                </small>
            </div>
        </form>
    </div>
</div>
<div class="mx-auto container border-top pt-2">
    <small class="text-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('users.signup') }}">Sign Up</a>
    </small>
    <br>
</div> -->
{% endblock %}

monitor/templates/monitoring.html
{% extends 'base.html' %}


{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col">
            <div class="container-fluid shadow-sm p-2 mb-5 bg-white rounded">
                <h5 class="card-header">Monitoring Dashboard</h5>
            </div>
            {{ website_url }}
        </div>
    </div>
</div>

{% endblock %}